version: "3"
services:
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    volumes:
      - ./model:/app
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
    ports:
      - "8888:8888"
